[PBIOS-476] Dark Mode Status Avatar Fix
powerhome/playbook-swift pull request #436
Opened 2024-08-13 16:39 UTC by RachelRadford21

**What does this PR do?**
[PBIOS-476] Dark Mode Status Avatar Fix

**Screenshots:**
![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-13 at 12 36 12](https://github.com/user-attachments/assets/ebdb8a54-527d-4c51-b74f-ccbe489b5d96)

![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-13 at 12 36 21](https://github.com/user-attachments/assets/20865072-8d4d-42cd-bd20-3b0b0ab000ec)

![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-13 at 12 36 24](https://github.com/user-attachments/assets/93cd76a8-7f49-4333-bb7e-9f748d4cdf64)

### Checklist
- [x] **LABELS** - Add a label: `breaking`, `bug`, `improvement`, `documentation`, or `enhancement`. See [Labels](https://github.com/powerhome/playbook-apple/labels) for descriptions.
- [x] **RELEASES** - Add the appropriate label: `Ready for Testing` / `Ready for Release`
- [x] **TESTING** - Have you tested your story?

2024-08-19 15:16 UTC, isismsilva requested changes

2024-08-19 15:16 UTC, isismsilva commented on Sources/Playbook/Design Elements/Colors/Color.xcassets/Borders/Border.colorset/Contents.json
why this color changed? Is this intended? It has design approval?

2024-08-19 15:35 UTC, RachelRadford21 commented on Sources/Playbook/Design Elements/Colors/Color.xcassets/Borders/Border.colorset/Contents.json
This can be ignored. I ended up making a border color extension and forgot to change this back.

2024-08-20 16:48 UTC, isismsilva approved these changes

2024-08-26 16:08 UTC, merged